# Generated by Django 4.2.2 on 2023-07-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GL_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GL_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GL_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IA_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IA_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IA_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IM_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IM_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.TimeField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IM_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('matricule', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SEIOT_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SEIOT_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SEIOT_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SI_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SI_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SI_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
                ('Professeur', models.CharField(max_length=64, null=True)),
                ('Groupe', models.IntegerField(default=1)),
            ],
        ),
    ]
