# Generated by Django 4.2.2 on 2023-06-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jours', models.CharField(max_length=64, null=True, unique=True)),
                ('Matières', models.CharField(max_length=64, null=True)),
                ('Heures', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('matricule', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
