# Generated by Django 4.2.2 on 2023-06-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('uname', models.CharField(max_length=300)),
                ('uemail', models.EmailField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
